### PR TITLE
Publish Examples with Latest Tag

### LINKED ISSUE #3020: (bug): Unable to pull bundles with latest tag
## Describe the bug
When pulling a bundle with `:latest` at the end, an additional `:` gets added 

## To Reproduce
```
porter install --force porter-hello --reference ghcr.io/getporter/examples/porter-hello:latest
unable to pull bundle: ghcr.io/getporter/examples/porter-hello:latest: not found
unable to pull bundle: ghcr.io/getporter/examples/porter-hello:latest: not found
```

## Expected behavior
Bundle properly gets downloaded

I'm assuming it is something within the `resolveBundleReference` function, and perhaps (since this was most recently touched) `ensureVPrefix` func.

### PR DESCRIPTION
**Pull request by kichristensen**
## Changes
- Modified `PublishExample` function to publish example bundles with both version-specific and latest tags
- Added error handling for the first publish operation

closes getporter/porter#3020

## Why
This change ensures that example bundles are available with both version-specific tags and a `latest` tag, making it easier for users to reference the most recent version of examples while maintaining version history.

## Impact
This change improves the usability of example bundles by providing a consistent way to reference the latest version while maintaining version history.

### CODE REVIEW

File: mage/setup/mixins.go [hunk 1]
```diff
@@ -25,12 +25,17 @@ func InstallMixins() error {
...
+			}
 			return porter.EnsureMixin(mixin)
 		})
 	}
 	return errG.Wait()
 }
 
 func EnsurePorter() {
-	porter.EnsurePorter()
+	porter.EnsurePorterAt("v1.2.1")
```
Comment (dgannon991) [inline mage/setup/mixins.go]: Is it worth updating the `DefaultPorterVersion` variable instead?

**Review by dgannon991 — COMMENTED** [review]
Only one thought, happy to be told it's not worth it!

File: mage/setup/mixins.go (hunk 1 above)
Comment (kichristensen) [reply mage/setup/mixins.go]: @dgannon991 Yes we probably should, but it requires the magefiles repository to be updated. I will create a PR for that, but I think it make sense to do it here for now to unblock.

Comment (dgannon991) [reply mage/setup/mixins.go]: @kichristensen Sorry, I know it's my fault, but is it worth changing this to 1.3.0?

Comment (kichristensen) [reply mage/setup/mixins.go]: @dgannon991 Good point :) I have just merged the update to magefiles, with should change the default version to 1.3.0, so this can be removed again, I will do that once the magefiles release have been created

**Comment by kichristensen** [comment]
@dgannon991 Please take a look again

**Review by dgannon991 — APPROVED** [review]
